modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
[[mods]]
modId = "botanicpledge"
version = "${file.jarVersion}"
displayName = "botanicpledge"
authors = "Yerova"
description = '''

'''
[[dependencies.botanicpledge]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicpledge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicpledge]]
modId = "botania"
mandatory = true
versionRange = "[1.20.1-441-FORGE]"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicpledge]]
modId = "curios"
mandatory = true
versionRange = "[5.4.2+1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.botanicpledge]]
modId = "patchouli"
mandatory = true
versionRange = "[1.20.1-83-FORGE]"
ordering = "NONE"
side = "BOTH"
