modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
[[mods]]
modId = "botanicpledge"
version = "${file.jarVersion}"
displayName = "botanicpledge"
authors = "Yerova"
description = '''

'''
[[dependencies.botanicpledge]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicpledge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicpledge]]
modId = "botania"
mandatory = true
versionRange = "[1.19.2-436-FORGE]"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicpledge]]
modId = "curios"
mandatory = true
versionRange = "[1.19.2-5.1.1.0]"
ordering = "NONE"
side = "BOTH"
[[dependencies.botanicpledge]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.2-77]"
ordering = "NONE"
side = "BOTH"
