name: Java CI with Gradle

on:
  push:
    branches: [ "1.20.1" ]
  pull_request:
    branches: [ "1.20.1" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Remove System.out.print statements
      run: |
        echo "Removing System.out.print and System.out.println statements..."
        find src/ -type f -name "*.java" -exec sed -i '/System\.out\.print/d' {} +
        echo "Finished removing System.out.print and System.out.println statements."

    - name: Grant execute permissions for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
